import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { emails, schedules, tasks } from "../data";
import { CounterCards, Button, CardWidget, EmailCard, ScheduleCard, TaskCard, ScheduleOptions } from '../components'
import { useState } from 'react';

export default function Home() {

  const [showSchedule, setShowSchedule] = useState(false);

  return (
    <div className={styles.container}>

      <Head>
        <title>Dawn Dashboard - Webflow HTML website template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>

        <div className={styles.space_between}>
          <h1>Dashboard</h1>
          <Button>Edit Dashboard</Button>
        </div>

        <div className={styles.homeCards}>

          <CounterCards title={"New Orders"} count={4} isActive />
          <CounterCards title={"New Customers"} count={12} />
          <CounterCards title={"Open Tickets"} count={23} />
          <CounterCards title={"On Hold"} count={8} />

        </div>

        <div className={styles.scheduleTasks}>
          <CardWidget
            cardHeader={"Schedule"}
            btnLabel={
              <div className={"scheduler_button"}>
                <p>Today </p>
                <Image src={"/images/caretDown.svg"} width={12} height={12} />
                <ScheduleOptions show={showSchedule} />
              </div>
            }
            btnAction={() => setShowSchedule(prevState => !prevState)}
            body={
              <div className={styles.scheduleBody}>
                {
                  schedules.map((item, index) => (
                    <ScheduleCard item={item} key={index} />
                  ))
                }
              </div>
            }
          />

          <CardWidget
            cardHeader={"Tasks"}
            btnLabel={"+"}
            body={
              <div>
                {
                  tasks.map((item, index) => (
                    <TaskCard item={item} key={index} />
                  ))
                }
              </div>
            }
          />
        </div>

        <div className={styles.emailTickets}>

          <CardWidget
            cardHeader={"Latest Emails"}
            btnLabel={"See All"}
            body={
              <div>
                {
                  emails.map((item, index) => (
                    <EmailCard
                      key={index}
                      item={item}
                    />
                  ))
                }
              </div>
            }
          />

          <CardWidget
            cardHeader={"New Tickets"}
            btnLabel={""}
            body={
              <div className={styles.tickets}>
                <Image src={"/images/ticks.svg"} width={50} height={32} />
                <p>No new <br />tickets</p>
              </div>
            }
          />

        </div>

      </>

      <footer className={styles.footer}>
        <span>&copy; Dawn All Rights Reserved{' '}</span>
        <span><a href={"https://oluwafemi-ayo.web.app"}>Built by Adegoke Joshua</a></span>
        <span>NextJS</span>
      </footer>

    </div >
  )
}
